version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.13.12
    - 7.13.8
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
